[package]
name = "xmas2025"
version = "0.1.0"
edition = "2024"

[dependencies]
ws281x-rpi = { version = "0.0.1" }
smart-leds = { version = "0.2.0" }
prisma = "0.1.1"
array2d = "0.3.2"
alpha-blend = "0.1.2"
rand = "0.9.2"

[features]
leds = []
no-display = []
terminal = []
